# Generated by Django 4.2.4 on 2023-08-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_category_type_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ImageField(blank=True, null=True, upload_to='category_Img'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_Img'),
        ),
    ]
