# Generated by Django 4.2.4 on 2023-08-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_category_type_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='img',
        ),
    ]
