# Generated by Django 4.2.4 on 2023-08-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_category_img_alter_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
