# Generated by Django 4.2.4 on 2023-08-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
