# Generated by Django 4.2.4 on 2023-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('productid', models.CharField(max_length=200)),
                ('vendorid', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('productprice', models.CharField(default='', max_length=200)),
                ('totalprice', models.CharField(max_length=200)),
            ],
        ),
    ]
