# Generated by Django 4.2.4 on 2023-08-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_vendorregister_rename_categoryname_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Vendorregister',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='categoryname',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoryname',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendorid',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='category_Img'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentamt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='product_Img'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='productid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='transactionid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='userid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
